import Head from 'next/head'
import Header from '../components/Header/Header'
import Main from '../components/Main/Main'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hulu by RQu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Navbar/>
      <Main/>
    </>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.genre;
  
}